### ISSUE TITLE
Support for BNI160?

### ISSUE THREAD

**Issue by hbjydev** [Smeltie/Hyperion#15]
Hey there,

Love the design of this case, it's the one I'd like to go with if I can have Thingiverse print it for me lol

Just wanted to know if the sizings would be compatible with a BNI160? That's the accelerometer I've got on order :)

Thanks!

**Comment by Smeltie** [comment]
Sadly the BMI does not fit but there should be a remix on thingiverse soon that accomodates it, saw someone working on it.

**Comment by hbjydev** [comment]
Oh, awesome. Thanks for the stupidly quick reply, I hadn't even closed the tab yet lol

**Comment by Smeltie** [comment]
I just so happened to look at that exact moment :)
