### ISSUE TITLE
903052 Case - Battery Slot Expansion

### ISSUE THREAD

**Issue by MellowMarble** [Smeltie/Hyperion#17]
I just got some of the [Amazon 903052s](https://www.amazon.com/dp/B088YKPZ9D/) linked from the SlimeVR [Components Guide](https://docs.slimevr.dev/diy/components-guide.html#components-guide) and most of them are measuring about 58-59mm long. Expanding the battery compartment to 60 mm gave them a good fit. I didn't file a PR since I'm not sure if you wanted these loose or friction tight. At 60mm..half fall out when turned upside down and the others come out with the slightest tap.

After Expanding the slot by 5mm to reach 60mm total:
![PXL_20221030_152944537](https://user-images.githubusercontent.com/26681997/198887189-a29d311a-cc5f-490b-b76b-007b454dddf6.jpg)

**Comment by vsmatthews** [comment]
hi! how did you print the hole thing? i also have de 903052. My switch is SS22F32 and the chip mpu6050.

**Comment by Smeltie** [comment]
seems more like the batteries off of amazon are mislabeled.
However since I have included all the files you should be able to edit them fairly easily with 1 or 2 extrude actions.
Apologies for the delayed reaction.
