### ISSUE TITLE
Tray_503759_BNO08x.stl

### ISSUE THREAD

**Issue by Originalas** [Smeltie/Hyperion#21]
MPU-9250 is a hair too tall to fit the 503759_BNO08x tray. The hole needs to be around 0.5mm taller.

![IMG_2596](https://user-images.githubusercontent.com/1495990/214518048-1fcea16b-a103-4b73-9a7e-3abe693dec3d.jpg)

**Comment by Smeltie** [comment]
That’s odd, they should be the same size as the BNO08X modules which are confirmed to fit.
This might be a different MPU9250 breakout manufacturer that uses different sizing/tolerances?

I am personally running these for my BNOs.
I’ve included the CAD files in this repo, you could fairly easily knock the wall back a hair to get your modules to fit.
Hope this helps!

**Comment by Originalas** [comment]
It's a very tight fit. :) It worked after little cleaning with a dremel. 
I guess, print has a little bit rounded corners and I smoothed the end of the board too. Maybe I will scale other prints to 102% size or something like that. 
 
![IMG_2608](https://user-images.githubusercontent.com/1495990/214607850-45dd706f-fc2e-424b-bd76-0d12e35f7d1a.jpg)
