### ISSUE TITLE
Small geometry issue with Case_804040_SS22F32.stl

### ISSUE THREAD

**Issue by timbit123** [Smeltie/Hyperion#7]
There is a small issue with the model and I could confirm in github stl viewer too

![image](https://user-images.githubusercontent.com/1305508/149836283-cb1cfe67-e212-4882-807b-571003cbff51.png)

you added a rectangle for the smaller battery but between that square and the wall, there is a hidden geometry with two holes that confuse a bit cura

Thanks,
Tim

**Comment by Smeltie** [comment]
I looked into it and yeah! there was in fact a small gap on all of the models.
Gap has since been filled and fixed.
Thank you for noticing and reporting this issue!

**Comment by timbit123** [comment]
I'm sorry but the issue still there
![image](https://user-images.githubusercontent.com/1305508/149843571-b8d2359f-e2c6-43da-aa96-f4fd19e5eb02.png)

**Comment by Smeltie** [comment]
> I'm sorry but the issue still there ![image](https://user-images.githubusercontent.com/1305508/149843571-b8d2359f-e2c6-43da-aa96-f4fd19e5eb02.png)

Ah we weren't talking about the same gap, there were actually 2.
Found it and should be fixed please let me know!

**Comment by Smeltie** [comment]
there appears to be another but after double checking in fusion and cura it can't be found anymore.
So i think it's something with the Github Viewer since the faces don't appear to exist anywhere else in particular.
